name: Actualizar tráfico Madrid

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script
        run: python generar_datos.py

      - name: Commit y push si hay cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add trafico_madrid_umap.geojson
          git commit -m "Actualizar tráfico Madrid" || echo "Sin cambios"
          git push
