name: Generar GeoJSON de Tráfico Madrid

on:
  schedule:
    - cron: "*/5 * * * *"  # Ejecuta cada 5 minutos (ajusta según sea necesario)
  push:
    branches:
      - main  # O la rama que prefieras
  workflow_dispatch:  # Permite ejecución manual desde la interfaz de GitHub

jobs:
  generar_geojson:
    runs-on: ubuntu-latest

    steps:
    - name: Check out el código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Puedes usar la versión que prefieras

    - name: Instalar dependencias
      run: |
        pip install --upgrade pip
        pip install requests  # Añadimos requests
        pip install pyproj  # Instala pyproj
        pip freeze  # Muestra las dependencias instaladas, para ver si requests está instalado

    - name: Instalar otras dependencias (si tienes un requirements.txt)
      run: pip install -r requirements.txt  # Si tienes otras dependencias

    - name: Ejecutar el script de generación de GeoJSON
      run: python generar_datos.py  # Aquí se ejecuta tu script Python

    - name: Configurar Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Añadir y hacer commit del archivo
      run: |
        git add trafico_madrid_umap.geojson
        git commit -m "Actualiza GeoJSON con nuevos datos de tráfico" || echo "Nada que commitear"

    - name: Hacer push
      run: git push
