name: Generar GeoJSON de Tráfico Madrid

on:
  schedule:
    - cron: "*/5 * * * *"  # Esto ejecutará el workflow cada 5 minutos (ajústalo según sea necesario)
  push:
    branches:
      - main  # O la rama que prefieras

jobs:
  generar_geojson:
    runs-on: ubuntu-latest

    steps:
    - name: Check out el código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Puedes usar la versión que prefieras

    - name: Instalar dependencias
      run: |
        pip install --upgrade pip
        pip install pyproj  # Instala pyproj
        pip freeze  # Muestra las dependencias instaladas, para ver si pyproj está instalado

    - name: Instalar otras dependencias (si tienes un requirements.txt)
      run: pip install -r requirements.txt  # Si tienes otras dependencias

    - name: Ejecutar el script de generación de GeoJSON
      run: python generar_datos.py  # Aquí se ejecuta tu script Python
